services:
    _defaults:
        autoconfigure: true
        autowire: true

    Adtechpotok\Bundle\EnqueueMessengerAdapterBundle\Command\AmqpUpdateCommand:
        arguments: [!tagged messenger.sender]

    Adtechpotok\Bundle\EnqueueMessengerAdapterBundle\EventSubscriber\QueueInteropTransportSubscriber: ~
