services:
    adtech.enqueue.messenger_transport.factory:
        class: 'Adtechpotok\Bundle\EnqueueMessengerAdapterBundle\Transport\QueueInteropTransportFactory'
        arguments:
            - '@messenger.transport.decoder'
            - '@messenger.transport.encoder'
            - '@service_container'
            - '%kernel.debug%'
        tags: [messenger.transport_factory]
